version: "3"

services:
  minks-corner:
    container_name: minks-corner-production
    image: minks-corner-development
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    ports:
      - "3000:3000"
