version: "3.9.5"

services:
  minks-corner:
    container_name: minks-corner-production
    image: minks-corner-production
    env_file: ../stack.env
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    pull_policy: build

networks:
  minks_corner_network:
    external: true
