version: "3.9.7"

services:
  minks-corner:
    container_name: minks-corner-production
    image: minks-corner-production
    # env_file:
    #   - ../../.env
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    pull_policy: build

networks:
  minks_corner_network:
    external: true
