version: "3.9.7"

services:
  minks-corner:
    container_name: minks-corner-production
    image: minks-corner-production
    # env_file:
    #   - ../../stack.env

    environment:
      - JWT_SECRET=$JWT_SECRET
      - NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
      - NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
      - NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
      args:
        JWT_SECRET: ${JWT_SECRET}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    restart: always
    ports:
      - "3000:3000"
    pull_policy: build

networks:
  minks_corner_network:
    external: true
